onflowser/flowser

- backend/src/blocks/blocks.controller.ts
- backend/src/blocks/blocks.module.ts
- backend/src/blocks/blocks.service.ts
- backend/src/blocks/entities/block.entity.ts
- backend/src/shared/interceptors/polling-response.interceptor.ts
- database/seeds/blocks.js
- database/seeds/transactions.js
- frontend/package.json
- frontend/src/core/components/subnavigation/SubNavigation.module.scss
- frontend/src/pages/blocks/Blocks.module.scss
- frontend/src/pages/blocks/Blocks.tsx
- frontend/src/shared/hooks/timeout-polling.ts
- Add polling interceptor
- Add polling hook
> - Add createdAt property to db seeds

- backend/src/blocks/entities/block.entity.ts
- frontend/src/pages/blocks/Blocks.tsx
- frontend/src/shared/hooks/filter-data.ts
- frontend/src/shared/hooks/timeout-polling.ts
Search filter hook which takes data stream (pooling data for example) and search term string (search bar for example) and 
provides another filtered stream which reacts on any of the two input streams.
> - Add filter data hook

- frontend/src/components/table/Table.tsx
- frontend/src/pages/accounts/main/Main.tsx
- frontend/src/utils/common-utils.ts
Updated table prop types to use existing react-table types.
> Fix Table component types

- backend/src/accounts/services/accounts.service.ts
- backend/src/common/common.module.ts
- backend/src/common/common.service.ts
- backend/src/flow/entities/snapshot.entity.ts
- backend/src/flow/flow.controller.ts
- backend/src/flow/flow.module.ts
- backend/src/flow/services/aggregator.service.ts
- backend/src/flow/services/snapshot.service.ts
- backend/src/projects/projects.module.ts
- backend/src/projects/projects.service.ts
- frontend/.eslintrc.js
- frontend/src/components/navigation/Navigation.tsx
- frontend/src/components/simple-button/SimpleButton.module.scss
- frontend/src/components/simple-button/SimpleButton.tsx
- frontend/src/hooks/use-api.ts
- frontend/src/hooks/use-timeout-polling.ts
- frontend/src/pages/blocks/main/Main.tsx
- frontend/src/services/snapshots.service.ts
- shared/package.json
- shared/proto/entities/snapshots.proto
- shared/proto/responses/snapshots.proto
- shared/src/types/index.ts
> Snapshot management functionality

- frontend/README.md
This milestone was completed by @monikaxh .
> Add links to UI design (Milestone 4)

- backend/src/transactions/entities/transaction.entity.ts
- frontend/src/components/ellipsis/Ellipsis.tsx
- frontend/src/components/table/Table.module.scss
- frontend/src/components/table/Table.tsx
- frontend/src/components/value/Value.tsx
- frontend/src/hooks/use-api.ts
- frontend/src/pages/accounts/details/Details.module.scss
- frontend/src/pages/accounts/details/Details.tsx
- frontend/src/pages/accounts/main/Main.module.scss
- frontend/src/pages/blocks/details/Details.module.scss
- frontend/src/pages/blocks/details/Details.tsx
- frontend/src/pages/blocks/main/Main.tsx
- frontend/src/pages/contracts/main/Main.module.scss
- frontend/src/pages/contracts/main/Main.tsx
- frontend/src/pages/events/Events.module.scss
- frontend/src/pages/events/Events.tsx
- frontend/src/pages/transactions/main/Main.tsx
I did some general updates to our tables across the app. 
Mostly I just removed/updated/reordered columns, but I also added a `className` option to our table column definition. This was implemented with the help of `columnDef.meta` attribute: https://tanstack.com/table/v8/docs/api/core/column-def#meta
> Updates to table columns

- frontend/src/App.tsx
- frontend/src/components/confirm-dialog/ConfirmDialog.tsx
- frontend/src/components/label/Label.module.scss
- frontend/src/components/label/Label.tsx
- frontend/src/components/navigation/Navigation.tsx
- frontend/src/components/sidebar/SideBar.tsx
- frontend/src/components/table/Table.tsx
- frontend/src/components/value/Value.module.scss
- frontend/src/components/value/Value.tsx
- frontend/src/contexts/confirm-dialog.context.tsx
- frontend/src/contexts/project-actions.context.tsx
- frontend/src/contexts/ui-state.context.tsx
- frontend/src/pages/events/Events.module.scss
- frontend/src/pages/events/Events.tsx
- frontend/src/pages/logs/Logs.module.scss
- frontend/src/pages/start/configuration/Configuration.tsx
- frontend/src/pages/start/main/Main.tsx
- frontend/src/pages/transactions/details/Details.module.scss
- frontend/src/utils/event-utils.ts
- add onClick handlers to sidebar buttons, which trigger project actions
- moved some logic from Navigation component into a shared "project actions" context
- remove legacy buttons and functions from Navigation component
- move confirm modal logic to a shared "confirm dialog" context
- updated events sub-table styles
- other minor improvements
> Sidebar updates, events sub-table updates, general refactorings

- frontend/src/App.scss
- frontend/src/pages/accounts/details/BaseStorageCard.module.scss
- frontend/src/pages/logs/Logs.module.scss
[Notion task.](https://www.notion.so/flowser/Update-scroll-bars-4537038434134c94905ec34b9d46bf4b)
> Updated scrollbar design

- frontend/public/index.html
- frontend/src/components/fullscreen-loading/FullScreenLoading.tsx
- frontend/src/components/input/Input.tsx
- frontend/src/components/layout/Layout.module.scss
- frontend/src/components/layout/Layout.tsx
- frontend/src/components/toggle-button/ToggleButton.tsx
- frontend/src/pages/accounts/Accounts.tsx
- frontend/src/pages/start/Start.tsx
- frontend/src/pages/start/configuration/Configuration.module.scss
- frontend/src/pages/start/configuration/Configuration.tsx
- frontend/src/pages/start/configuration/ConfigurationSection.module.scss
- frontend/src/pages/start/configuration/ConfigurationSection.tsx
- frontend/src/pages/start/configuration/FormFields.module.scss
- frontend/src/pages/start/configuration/FormFields.tsx
- frontend/src/pages/start/main/Main.module.scss
- frontend/src/pages/start/main/Main.tsx
There are still some things to improve/fix, but it's mostly ready.
[Notion task.](https://www.notion.so/flowser/Update-details-screens-345b34af6419452fb816c1ee8c18f40b)
**Changelist:**
- Completely rewritten configuration screen styles - making them simpler and more maintainable
- Refactored settings components to seperate components (with isolated styles)
- Updated UI design
https://user-images.githubusercontent.com/36109955/189143097-3218d3b7-c452-4b39-ac34-bc45a63e4681.mov
> Refactored project configuration, updated design

- backend/src/accounts/services/storage.service.ts
- frontend/src/pages/accounts/details/BaseStorageCard.module.scss
- frontend/src/pages/accounts/details/BaseStorageCard.tsx
- frontend/src/pages/accounts/details/Details.tsx
- frontend/src/pages/accounts/details/PublicPrivateStorageCard.module.scss
- frontend/src/pages/accounts/details/PublicPrivateStorageCard.tsx
I minted a new NFT on the service account, but Flowser doesn’t show up-to-date account storage state for private and public paths.
> Fix private/public storage indexing

- backend/src/flow/services/gateway.service.ts
- frontend/src/targets/electron/main.ts
> Fix invalid account balance

- backend/src/accounts/services/accounts.service.ts
- backend/src/data-processing/processor.service.ts
- backend/src/utils.ts
Resolve: https://github.com/onflowser/flowser/issues/161
> Fix Flow token balances not updated

- backend/src/utils.spec.ts
- backend/src/utils.ts
Resolve: https://github.com/onflowser/flowser/issues/160
> Fix updated account storage not reflected

- backend/src/flow/services/config.service.ts
- frontend/src/pages/accounts/details/Details.tsx
- frontend/src/pages/accounts/details/InternalStorageCard.tsx
- frontend/src/pages/accounts/details/PublicPrivateStorageCard.tsx
Resolve: https://github.com/onflowser/flowser/issues/158
> Fix invalid private/public storage link

- frontend/src/contexts/timeout-polling.context.tsx
- frontend/src/hooks/use-api.ts
- frontend/src/hooks/use-flow.ts
- frontend/src/utils/flow-utils.ts
It seems like the react-query library is having some weird behavior that wasn't seen previously. This is just a temporary fix for now, we should revisit this in the future.
See: https://www.notion.so/flowser/react-query-weird-behavior-d40ea15498b740b6899be3e42cb32945?pvs=4
Implemented in the scope of: https://github.com/onflow/developer-grants/issues/150
> Fix initial loading

- frontend/src/targets/electron/backend.ts
- frontend/src/targets/electron/main.ts
This was a regression due to some new logic:
- we don't automatically redirect you to the project page if current project is found - this caused it to not open the temporary project in Flowser once it started
- we added strict type checking and start throwing error if something isn't provided but should be - this threw an error when creating a temporary project, but where path wasn't yet known
> Fix temporary project startup regression

- apps/electron/src/main/ipc/handlers.ts
- apps/electron/src/services/flowser-app.service.ts
- apps/electron/src/services/workspace.service.ts
- packages/core/src/fcl-value.ts
- packages/nodejs/src/flow-cli.service.ts
- packages/nodejs/src/flow-config.service.ts
- packages/ui/package.json
- packages/ui/src/api.ts
- packages/ui/src/common/loaders/Shimmer/Shimmer.tsx
- packages/ui/src/common/status/ErrorMessage.tsx
- packages/ui/src/interactions/components/InteractionLabel/InteractionLabel.tsx
- packages/ui/src/interactions/components/InteractionTemplates/InteractionTemplates.tsx
- packages/ui/src/interactions/components/ValueBuilder/AddressBuilder/AddressBuilder.tsx
- packages/ui/src/interactions/components/ValueBuilder/ValueBuilder.tsx
- packages/ui/src/interactions/hooks/use-transaction-name.ts
- yarn.lock
Various bug fixes and improvements.
> Polish 10/3

- apps/electron/src/renderer/components/DependencyErrors/DependencyErrors.tsx
- apps/electron/src/services/flowser-app.service.ts
- apps/electron/src/services/workspace.service.ts
- packages/nodejs/src/flow-config.service.ts
- packages/nodejs/src/flow-emulator.service.ts
- packages/nodejs/src/processes/managed-process.ts
- packages/ui/src/common/status/ErrorMessage.tsx
- packages/ui/src/interactions/components/ValueBuilder/AddressBuilder/AddressBuilder.tsx
Restart the emulator and reconfigure related services when workspace settings are updated.
> Handle workspace settings update

- packages/ui/package.json
- packages/ui/src/accounts/InternalStorageCard/InternalStorageCard.module.scss
- packages/ui/src/accounts/InternalStorageCard/InternalStorageCard.tsx
- packages/ui/src/accounts/PublicPrivateStorageCard/PublicPrivateStorageCard.module.scss
- packages/ui/src/accounts/PublicPrivateStorageCard/PublicPrivateStorageCard.tsx
- packages/ui/src/api.ts
- packages/ui/src/common/icons/TokenIcon/TokenIcon.tsx
- packages/ui/src/common/links/ExternalLink/ExternalLink.tsx
- packages/ui/src/contracts/ContractDetails/ContractDetails.tsx
- packages/ui/src/contracts/ContractName/ContractName.module.scss
- packages/ui/src/contracts/ContractName/ContractName.tsx
- packages/ui/src/contracts/ContractsTable/ContractsTable.tsx
- yarn.lock
Integrate token metadata from https://github.com/FlowFans/flow-token-list.
Show token logo + links in contract details:
Show logo in table:
Show logo in storage items tied to that contract:
Developed in the scope of Community 2 Community milestone of https://github.com/onflow/developer-grants/issues/150
> Add token metadata

- apps/electron/src/renderer/router.tsx
- packages/ui/src/api.ts
- packages/ui/src/contracts/ContractDetails/ContractDetails.tsx
- packages/ui/src/transactions/TransactionDetailsTabs/TransactionDetailsTabs.tsx
Show a list of events, emitted by a contract, on contract details page:
> Show events in contract details

- packages/ui/src/common/cards/DetailsCard/DetailsCard.tsx
- packages/ui/src/common/links/ExternalLink/ExternalLink.tsx
- packages/ui/src/contracts/ContractDetails/ContractDetails.module.scss
- packages/ui/src/contracts/ContractDetails/ContractDetails.tsx
- yarn.lock
If token metadata isn't found for fungible token contracts, show prompt with a link to https://github.com/FlowFans/flow-token-list.
> Prompt token metadata creation

- apps/electron/electron-builder.yml
- apps/electron/src/services/flowser-app.service.ts
- packages/nodejs/build-go-bindings.sh
- packages/nodejs/src/go-bindings.service.ts
- pkg/flowser/app.go
- pkg/main/main.go
- Update our go lib to work on Linux
- add support for arm64 and amd64 architectures on all platforms
> Support install/run on Linux, extend arch support

- apps/web/package.json
- packages/ui/src/interactions/InteractionsPage.tsx
- packages/ui/src/interactions/components/SaveSnippetDialog/SaveSnippetDialog.tsx
Previously you couldn't update the snippet name at the time of saving.
> Fix snippet saving

- apps/web/src/common/root.tsx
- packages/ui/src/api.ts
- packages/ui/src/interactions/InteractionsPage.tsx
- packages/ui/src/interactions/components/InteractionHistory/InteractionHistory.tsx
- packages/ui/src/interactions/components/InteractionLabel/InteractionLabel.tsx
- packages/ui/src/interactions/components/InteractionTemplates/InteractionTemplates.tsx
- packages/ui/src/interactions/contexts/interaction-registry.context.tsx
- packages/ui/src/interactions/contexts/templates.context.tsx
- packages/ui/src/interactions/core/core-types.ts
- packages/ui/src/transactions/TransactionSource/TransactionSource.tsx
Task: https://www.notion.so/flowser/Update-URL-when-setting-focused-interaction-423fdf066fb6435cb60eeb0318840b19?pvs=4
> Sync URL with currently focused interaction
